chore: added validator path
Informasjonsforvaltning/fdk-nginx-search pull request #46
Opened 2021-01-11 14:25 UTC by valosnah

2021-01-11 15:50 UTC, jeffreiffers commented on nginx-prod.conf
> +            proxy_pass http://dcat-ap-no-validator-gui:8080/validator;
```suggestion
            proxy_pass http://dcat-ap-no-validator-gui:8080;
```

2021-01-11 15:51 UTC, jeffreiffers requested changes

2021-01-11 15:51 UTC, jeffreiffers commented on nginx.conf
> +            proxy_pass http://dcat-ap-no-validator-gui:8080/validator;
```suggestion
            proxy_pass http://dcat-ap-no-validator-gui:8080;
```

2021-01-13 11:35 UTC, azaxarov approved these changes

2021-01-29 11:30 UTC, merged